spring.application.name=demo
server.port=9090
spring.jackson.deserialization.fail-on-null-for-primitives=false

mqtt.broker-url=tcp://broker.hivemq.com:1883
mqtt.topic.portao=securyentry/xk92mf7t/portao/cmd
